version: '3.9'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
    #environment:
      #POSTGRES_USER: admin
      #POSTGRES_PASSWORD: 12345
      #POSTGRES_DB: my_database
    ports:
      - "8000:8000"
    #depends_on:
    #  - postgres
    networks:
      - network

  #postgres:
  #  image: postgres:latest
  #  container_name: my_postgres
  #  environment:
  #    POSTGRES_USER: admin
  #    POSTGRES_PASSWORD: 12345
  #    POSTGRES_DB: my_database
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #  networks:
  #    - network

#volumes:
#  postgres_data:

networks:
  network:
    driver: bridge
