version: '3.9'

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - network

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge