# Generated by Django 3.2.23 on 2023-12-28 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Скрыть пункт меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_main_menu',
            field=models.BooleanField(default=True, verbose_name='Главное меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainweb.page', verbose_name='Связь с Page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainweb.menuitem', verbose_name='Родительский элемент'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок пункта меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Скрыть модуль'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='body',
            field=models.TextField(verbose_name='Основной текст модуля'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок модуля'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(verbose_name='Основной текст стр-цы:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(max_length=550, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='keywords',
            field=models.CharField(max_length=250, verbose_name='Keywords:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Публикация:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seotitle',
            field=models.CharField(max_length=250, verbose_name='Title:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='URL страницы:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена:'),
        ),
    ]
