# Generated by Django 3.2.23 on 2023-12-30 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0002_auto_20231228_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mainweb.page'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
