# Generated by Django 3.2.23 on 2024-01-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0004_auto_20231231_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Опубликована:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры:'),
        ),
    ]
