# Generated by Django 3.2.23 on 2024-01-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0005_auto_20240101_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modul',
            options={'verbose_name': 'модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id'], 'verbose_name': 'страницу', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='modul',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Опубликована:'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Заголовок:'),
        ),
        migrations.AlterIndexTogether(
            name='modul',
            index_together={('id', 'title')},
        ),
        migrations.RemoveField(
            model_name='modul',
            name='active',
        ),
    ]
